sudo: false
cache: pip
language: python
python:
  - '3.7'
stages:
  - lint
  - docs
  - test
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=pyroma
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py
    - env: TOXENV=py PATHME_TESTS=tests/test_kegg/
install:
  - pip install tox
  - pip install codecov
  - pip install coverage
script:
  - tox
after_success:
  - tox -e coverage-report
  - codecov
notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
